App_auth/urls.py
from django.urls import path
from . import views


app_name = 'App_auth'

urlpatterns = [
    path('admin-signup/', views.admin_signup, name='admin-signup'),
    path('trainer-signup/', views.trainer_signup, name='trainer-signup'),
    path('member-signup/', views.member_signup, name='member-signup'),
    path('login/', views.login_system, name='login'),
    path('log-out/', views.logout_system, name='log-out'),

]

App_main/urls.py
from django.urls import path
from . import views


app_name = 'App_main'

urlpatterns = [
    path('', views.index, name='index'),
    path('member-dashboard', views.member_dashboard, name='member-dashboard'),
    path('admin-dashboard', views.admin_dashboard, name='admin-dashboard'),
    path('assign-trainers', views.assign_trainers, name='assign-trainers'),
    path('total-members', views.total_members, name='total-members'),
    path('health-check', views.health_check, name='health-check'),
    path('diet-chart', views.diet_chart, name='diet-chart'),

]

App_main/models.py
from django.db import models

# Create your models here.

App_main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test

# Create your views here.
from App_auth.models import MemberModel, AdminModel


def is_admin(user):
    return user.groups.filter(name='ADMIN').exists()


def is_trainer(user):
    return user.groups.filter(name='TRAINER').exists()


def is_member(user):
    return user.groups.filter(name='MEMBER').exists()


def index(request):
    return render(request, 'App_main/index.html')


@login_required(login_url='App_auth:login')
@user_passes_test(is_member)
def member_dashboard(request):
    profile = MemberModel.objects.get(user=request.user)
    content = {
        'profile': profile,
    }
    return render(request, 'App_main/member_dashboard.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_member)
def health_check(request):
    return render(request, 'App_main/health_check.html')


@login_required(login_url='App_auth:login')
@user_passes_test(is_member)
def diet_chart(request):
    return render(request, 'App_main/diet_chart.html')



# ------------------------------------------------member end-------------------------------------------
# ------------------------------------------------admin start-------------------------------------------

@login_required(login_url='App_auth:login')
@user_passes_test(is_admin)
def admin_dashboard(request):
    profile = AdminModel.objects.get(user=request.user)
    members = MemberModel.objects.all()
    content = {
        'profile': profile,
        'members': members.count(),
    }
    return render(request, 'App_main/admin_dashboard.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_admin)
def assign_trainers(request):
    members = MemberModel.objects.filter(my_trainer=None)
    content = {
        'members': members,
    }
    return render(request, 'App_main/assign_trainers.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_admin)
def total_members(request):
    members = MemberModel.objects.all()
    content = {
        'members': members
    }
    return render(request, 'App_main/total_members.html', context=content)

templates/App_main/admin_dashboard.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>GWTS | Dashboard</title>
</head>
<body>
<style>
    @import url("https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;700&display=swap");
    @import url("https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;700&display=swap");

    .badge {
        position: fixed;
        bottom: 20px;
        right: 20px;
        cursor: pointer;
        z-index: 999;
    }

    .container {
        display: flex;
        flex-direction: column-reverse;
        font-family: "Nunito", sans-serif;
        width: 100%;
    }

    .profile {
        width: 50px;
        height: 50px;
        border-radius: 50%;
        -webkit-box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        transition: all 0.5s ease-in-out;
        background-image: url("https://assets.codepen.io/4826739/MicrosoftTeams-image+%281%29.png");
        background-repeat: no-repeat;
        background-size: cover;
    }

    .profile:hover {
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
        cursor: context-menu;
    }

    .profile:hover::before {
        opacity: 1;
    }

    .logout {
        border: 1px solid white;
        padding: 5px;
        border-radius: 20%;
        font-weight: bold;
        background-color: black;
    }
    .logout:hover {
        color: #f56040;
    }

    a {
        text-decoration: none;
        text-align: center;
    }

    .ig {
        height: 50px;
        width: 50px;
        border-radius: 50%;
        background: #f56040;
        -webkit-box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        transition: all 0.5s ease-in-out;
    }

    .ig:hover {
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
        transform: rotatez(-10deg);
    }

    .ig:hover::before {
        opacity: 1;
    }

    .ig::before {
        position: absolute;
        right: 60px;
        color: white;
        content: "Instagram";
        opacity: 0;
        transition: all 0.5s ease-in-out;
        background: black;
        padding: 5px 10px;
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
    }

    .blog {
        height: 50px;
        width: 50px;
        border-radius: 50%;
        background: black;
        -webkit-box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        transition: all 0.5s ease-in-out;
    }

    .blog:hover {
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
        transform: rotatez(-10deg);
    }

    .blog:hover::before {
        opacity: 1;
    }

    .blog::before {
        position: absolute;
        right: 60px;
        color: white;
        content: "Github";
        opacity: 0;
        transition: all 0.5s ease-in-out;
        background: black;
        padding: 5px 10px;
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
    }

    .tw {
        height: 50px;
        width: 50px;
        border-radius: 50%;
        background: #1da1f2;
        -webkit-box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        transition: all 0.5s ease-in-out;
    }

    .tw:hover {
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
        transform: rotatez(-10deg);
    }

    .tw:hover::before {
        opacity: 1;
    }

    .tw::before {
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
        position: absolute;
        right: 60px;
        color: white;
        content: "Twitter";
        opacity: 0;
        transition: all 0.5s ease-in-out;
        background: black;
        padding: 5px 10px;
    }

    .li {
        height: 50px;
        width: 50px;
        border-radius: 50%;
        background: #1da1f2;
        -webkit-box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        transition: all 0.5s ease-in-out;
    }

    .li:hover {
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
        transform: rotatez(-10deg);
    }

    .li:hover::before {
        opacity: 1;
    }

    .li::before {
        position: absolute;
        right: 60px;
        color: white;
        content: "LinkedIn";
        opacity: 0;
        transition: all 0.5s ease-in-out;
        background: black;
        padding: 5px 10px;
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
    }

    .margin {
        margin-bottom: 10px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    svg {
        width: 25px;
        fill: white;
    }

    @media only screen and (max-height: 350px) {
        .container {
            flex-direction: row-reverse;
        }

        .margin {
            margin-bottom: 0px;
            margin-left: 10px;
        }

        .profile::before,
        .ig::before,
        .tw::before,
        .li::before,
        .blog::before {
            right: 0px;
            top: -40px;
        }
    }

    body {
        margin: 0;
        font-family: "Nunito", sans-serif;
        background: linear-gradient(90deg, #4b6cb7 0%, #182848 100%);
    }

    body a {
        color: white;
        text-decoration: none;
    }

    .container {
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        width: 100% !important;
    }

    .overview {
        display: grid;
        height: 100%;
        width: 97%;
        grid-template-columns: 1fr 1fr 1fr 1fr;
        grid-template-rows: 1fr 1fr 1fr 0.1fr;
        background-color: #040404;
        color: #FFFFFF;
        border: 10px solid black;
        padding: 10px;
        -webkit-box-shadow: 4px 7px 26px 2px rgba(0, 0, 0, 0.53);
        box-shadow: 4px 7px 26px 2px rgba(0, 0, 0, 0.53);
    }

    .tile {
        background: black;
        background: linear-gradient(157deg, black 0%, #242424 100%);
        border-radius: 5px;
        margin: 5px;
        padding: 20px;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        transition: all ease-in-out 1s;
    }

    .tile h2 {
        cursor: pointer;
    }

    .icosvg {
        height: 70px;
        width: 70px;
        fill: white;
        transform: translatey(20px);
        cursor: pointer;
    }

    .active {
        background: linear-gradient(157deg, #823918 0%, #e96a2f 100%);
    }

    .w1x1 {
        grid-column: span 1;
    }

    .w1x2 {
        grid-column: span 2;
    }

    .w1x3 {
        grid-column: span 3;
    }

    .w1x4 {
        grid-column: span 4;
    }

    .inner-1x {
        display: grid;
        grid-template-columns: 1fr;
    }

    .inner-2x {
        display: grid;
        grid-template-columns: 1fr 1fr;
    }

    .inner-3x {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
    }

    .center {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .icon {
        width: 100px;
        height: 100px;
    }

    .accent-text {
        color: #d05a24;
    }

    .footer {
        grid-column: span 4;
        margin-left: 5px;
        margin-right: 5px;
        color: #d05a24;
        font-size: 10px;
        display: flex;
        flex-direction: row;
    }

    .link-orange {
        background: linear-gradient(157deg, #9d6916 0%, #ffa91f 100%);
        color: #FFFFFF;
        padding: 2px 5px;
        float: right;
        margin-left: 5px;
        cursor: pointer;
    }

    .link-blue {
        background: linear-gradient(157deg, #829c96 0%, #bbe4db 100%);
        color: #FFFFFF;
        padding: 2px 5px;
        float: right;
        margin-left: 5px;
        cursor: pointer;
    }

    .link-red {
        background: linear-gradient(157deg, #983122 0%, #ff4e33 100%);
        color: #FFFFFF;
        padding: 2px 5px;
        float: right;
        margin-left: 5px;
        cursor: pointer;
    }

    .link-white {
        background: #FFFFFF;
        color: #040404;
        padding: 2px 5px;
        float: right;
        margin-left: 5px;
    }

    .icons {
        flex: 1;
    }

    .icon-bottom {
        fill: #d05a24;
        width: 17px;
        height: 17px;
        margin-right: 10px;
        cursor: pointer;
    }
</style>

<div class="container">

    <div class="overview">
        <div class="tile w1x3 inner-2x">
      <span>
      <h1>GWTS | Dashboard</h1>
      <h1 class="accent-text">{{ profile.user.first_name }} {{ profile.user.last_name }}</h1>
      </span>
            <div class="inner-2x">
        <span class="center">
          <img src="{{ profile.profile_picture.url }}" height="200px" width="200px" alt="profile picture"/>
        </span>
        <span style="font-size: 16px">
          <p>Joined: {{ profile.joining_date }}</p><hr>
            <p>Phone: {{ profile.phone_number }}</p><hr>
            <p>Address: {{ profile.address }}</p>
            <a href="{% url 'App_auth:log-out' %}" class="logout">Log Out</a>
        </span>
            </div>
        </div>
        <div class="tile w1x1 active " id="livingroom">
            <a href="{% url 'App_main:assign-trainers' %}">
            <img src="https://static.wixstatic.com/media/47e4b9_e124e88fcc6348f7aaf0aafea0b5ea84~mv2.png/v1/fill/w_254,h_254,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/47e4b9_e124e88fcc6348f7aaf0aafea0b5ea84~mv2.png" height="120px" width="150px" style="margin-top: 0px!important;">
            <h2 style="margin-top: 0px!important;margin-bottom: 0px!important;">Assign Trainers</h2>
            </a>
        </div>
        <div class="tile w1x2">
            <a href="{% url 'App_main:total-members' %}">
            <h1  style="margin-top: 0px!important;">Total Members</h1>
            <h2 style="margin-top: 0px!important; margin-bottom: 0px!important;">{{ members }}</h2>
            </a>
        </div>
        <div class="tile w1x1" id="bedroom">
            <a href="{% url 'App_auth:trainer-signup' %}">
                <img src="{% static 'img/hero/trainer.png' %}" height="150px" width="150px">
                <h2 style="margin-top: 0px!important;">Add Trainer</h2>
            </a>
        </div>
        <div class="tile w1x1" id="hallway">
            <a href="{% url 'App_auth:admin-signup' %}">
                <img src="{% static 'img/hero/admin-1.png' %}" height="150px" width="150px"  style="margin-top: 0px!important; margin-bottom: 0px!important;">
                <h2 style="margin-top: 0px!important;">Add Admin</h2>
            </a>
        </div>
        <div class="tile w1x1" id="assistant">
            <a href="">
            <img src="{% static 'img/hero/announce.png' %}" height="120px" width="150px"  style="margin-top: 0px!important; margin-bottom: 0px!important;">
            <h2>Announcements</h2>
            </a>
        </div>
        <div class="tile w1x2 active">
            <a href="">
            <h1>Health Blogs</h1>
            </a>
        </div>
        <div class="tile w1x1" id="television">
           <img src="{% static 'img/hero/stat.png' %}" height="120px" width="150px"  style="margin-top: 0px!important; margin-bottom: 0px!important;">
            <h2>statistics</h2>
        </div>

    </div>
</div>
</body>
</html>

templates/App_main/member_dashboard.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>GWTS | Dashboard</title>
</head>
<body>
<style>
    @import url("https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;700&display=swap");
    @import url("https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;700&display=swap");

    .badge {
        position: fixed;
        bottom: 20px;
        right: 20px;
        cursor: pointer;
        z-index: 999;
    }

    .container {
        display: flex;
        flex-direction: column-reverse;
        font-family: "Nunito", sans-serif;
        width: 100%;
    }

    .profile {
        width: 50px;
        height: 50px;
        border-radius: 50%;
        -webkit-box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        transition: all 0.5s ease-in-out;
        background-image: url("https://assets.codepen.io/4826739/MicrosoftTeams-image+%281%29.png");
        background-repeat: no-repeat;
        background-size: cover;
    }

    .profile:hover {
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
        cursor: context-menu;
    }

    .profile:hover::before {
        opacity: 1;
    }

    .logout {
        border: 1px solid white;
        padding: 5px;
        border-radius: 20%;
        font-weight: bold;
        background-color: black;
    }
    .logout:hover {
        color: #f56040;
    }

    .ig {
        height: 50px;
        width: 50px;
        border-radius: 50%;
        background: #f56040;
        -webkit-box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        transition: all 0.5s ease-in-out;
    }

    .ig:hover {
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
        transform: rotatez(-10deg);
    }

    .ig:hover::before {
        opacity: 1;
    }

    .ig::before {
        position: absolute;
        right: 60px;
        color: white;
        content: "Instagram";
        opacity: 0;
        transition: all 0.5s ease-in-out;
        background: black;
        padding: 5px 10px;
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
    }

    .blog {
        height: 50px;
        width: 50px;
        border-radius: 50%;
        background: black;
        -webkit-box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        transition: all 0.5s ease-in-out;
    }

    .blog:hover {
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
        transform: rotatez(-10deg);
    }

    .blog:hover::before {
        opacity: 1;
    }

    .blog::before {
        position: absolute;
        right: 60px;
        color: white;
        content: "Github";
        opacity: 0;
        transition: all 0.5s ease-in-out;
        background: black;
        padding: 5px 10px;
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
    }

    .tw {
        height: 50px;
        width: 50px;
        border-radius: 50%;
        background: #1da1f2;
        -webkit-box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        transition: all 0.5s ease-in-out;
    }

    .tw:hover {
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
        transform: rotatez(-10deg);
    }

    .tw:hover::before {
        opacity: 1;
    }

    .tw::before {
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
        position: absolute;
        right: 60px;
        color: white;
        content: "Twitter";
        opacity: 0;
        transition: all 0.5s ease-in-out;
        background: black;
        padding: 5px 10px;
    }

    .li {
        height: 50px;
        width: 50px;
        border-radius: 50%;
        background: #1da1f2;
        -webkit-box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        box-shadow: 1px 1px 14px -2px rgba(0, 0, 0, 0.6);
        transition: all 0.5s ease-in-out;
    }

    .li:hover {
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
        transform: rotatez(-10deg);
    }

    .li:hover::before {
        opacity: 1;
    }

    .li::before {
        position: absolute;
        right: 60px;
        color: white;
        content: "LinkedIn";
        opacity: 0;
        transition: all 0.5s ease-in-out;
        background: black;
        padding: 5px 10px;
        -webkit-box-shadow: 1px 1px 14px -2px #000000;
        box-shadow: 1px 1px 14px -2px #000000;
    }

    .margin {
        margin-bottom: 10px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    svg {
        width: 25px;
        fill: white;
    }

    @media only screen and (max-height: 350px) {
        .container {
            flex-direction: row-reverse;
        }

        .margin {
            margin-bottom: 0px;
            margin-left: 10px;
        }

        .profile::before,
        .ig::before,
        .tw::before,
        .li::before,
        .blog::before {
            right: 0px;
            top: -40px;
        }
    }

    body {
        margin: 0;
        font-family: "Nunito", sans-serif;
        background: linear-gradient(90deg, #4b6cb7 0%, #182848 100%);
    }

    body a {
        color: white;
        text-decoration: none;
    }

    .container {
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        width: 100% !important;
    }

    .overview {
        display: grid;
        height: 100%;
        width: 97%;
        grid-template-columns: 1fr 1fr 1fr 1fr;
        grid-template-rows: 1fr 1fr 1fr 0.1fr;
        background-color: #040404;
        color: #FFFFFF;
        border: 10px solid black;
        padding: 10px;
        -webkit-box-shadow: 4px 7px 26px 2px rgba(0, 0, 0, 0.53);
        box-shadow: 4px 7px 26px 2px rgba(0, 0, 0, 0.53);
    }

    .tile {
        background: black;
        background: linear-gradient(157deg, black 0%, #242424 100%);
        border-radius: 5px;
        margin: 5px;
        padding: 20px;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        transition: all ease-in-out 1s;
    }

    .tile h2 {
        cursor: pointer;
    }

    .icosvg {
        height: 70px;
        width: 70px;
        fill: white;
        transform: translatey(20px);
        cursor: pointer;
    }

    .active {
        background: linear-gradient(157deg, #823918 0%, #e96a2f 100%);
    }

    .w1x1 {
        grid-column: span 1;
    }

    .w1x2 {
        grid-column: span 2;
    }

    .w1x3 {
        grid-column: span 3;
    }

    .w1x4 {
        grid-column: span 4;
    }

    .inner-1x {
        display: grid;
        grid-template-columns: 1fr;
    }

    .inner-2x {
        display: grid;
        grid-template-columns: 1fr 1fr;
    }

    .inner-3x {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
    }

    .center {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .icon {
        width: 100px;
        height: 100px;
    }

    .accent-text {
        color: #d05a24;
    }

    .footer {
        grid-column: span 4;
        margin-left: 5px;
        margin-right: 5px;
        color: #d05a24;
        font-size: 10px;
        display: flex;
        flex-direction: row;
    }

    .link-orange {
        background: linear-gradient(157deg, #9d6916 0%, #ffa91f 100%);
        color: #FFFFFF;
        padding: 2px 5px;
        float: right;
        margin-left: 5px;
        cursor: pointer;
    }

    .link-blue {
        background: linear-gradient(157deg, #829c96 0%, #bbe4db 100%);
        color: #FFFFFF;
        padding: 2px 5px;
        float: right;
        margin-left: 5px;
        cursor: pointer;
    }

    .link-red {
        background: linear-gradient(157deg, #983122 0%, #ff4e33 100%);
        color: #FFFFFF;
        padding: 2px 5px;
        float: right;
        margin-left: 5px;
        cursor: pointer;
    }

    .link-white {
        background: #FFFFFF;
        color: #040404;
        padding: 2px 5px;
        float: right;
        margin-left: 5px;
    }

    .icons {
        flex: 1;
    }

    .icon-bottom {
        fill: #d05a24;
        width: 17px;
        height: 17px;
        margin-right: 10px;
        cursor: pointer;
    }
</style>

<div class="container">

    <div class="overview">
        <div class="tile w1x3 inner-2x">
      <span>
      <h1>GWTS | Dashboard</h1>
      <h1 class="accent-text">{{ profile.user.first_name }} {{ profile.user.last_name }}</h1>
      </span>
            <div class="inner-2x">
        <span class="center">
          <img src="{{ profile.profile_picture.url }}" height="200px" width="200px" alt="profile picture"/>
        </span>
        <span style="font-size: 14px">
          <p>Joined: {{ profile.joining_date }}</p><hr>
            <p>Phone: {{ profile.phone_number }}</p><hr>
            <p>Address: {{ profile.address }}</p>
            <a href="{% url 'App_auth:log-out' %}" class="logout">Log Out</a>
        </span>
            </div>
        </div>
        <div class="tile w1x1 active " id="livingroom">
            <a href="">
            <img src="https://static.wixstatic.com/media/47e4b9_e124e88fcc6348f7aaf0aafea0b5ea84~mv2.png/v1/fill/w_254,h_254,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/47e4b9_e124e88fcc6348f7aaf0aafea0b5ea84~mv2.png" height="120px" width="150px" style="margin-top: 0px!important;">
            <h2 style="margin-top: 0px!important;margin-bottom: 0px!important;">My Trainer</h2>
            </a>
        </div>
        <div class="tile w1x2" style="text-align: center">
            <a href="{% url 'App_main:health-check' %}">
            <h1  style="margin-top: 0px!important;">Health Check</h1>
            <h5 style="margin-top: 0px!important; margin-bottom: 0px!important;">Health Status</h5>
            </a>
        </div>
        <div class="tile w1x1" id="bedroom" style="text-align: center">
            <a href="{% url 'App_main:diet-chart' %}">
            <img src="{% static 'img/hero/diet-1.png' %}" height="50px" width="50px">
            <h2 style="margin-bottom: 0px!important;">Diet Chart</h2>
            </a>
        </div>
        <div class="tile w1x1" id="hallway">
            <img src="{% static 'img/hero/trainer.png' %}" height="120px" width="150px"  style="margin-top: 0px!important; margin-bottom: 0px!important;">
            <h2 style="margin-top: 0px!important;">My Targets</h2>
        </div>
        <div class="tile w1x1" id="assistant">
            <svg class="icosvg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21 21">
                <g fill="none" fill-rule="evenodd" transform="translate(3 3)">
                    <path d="m8 13.5172414c4.418278 0 8-3.0259376 8-6.75862071 0-3.73268314-3.581722-6.75862069-8-6.75862069s-8 3.02593755-8 6.75862069c0 1.45741942.5460328 2.80709561 1.47469581 3.91098161l-.97469581 4.5803977 3.91607376-2.4472652c1.07810761.4571647 2.29544433.7145066 3.58392624.7145066z"
                          stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
                    <path d="m7.99884033 8c.5 0 1-.5 1-1s-.5-1-1-1-.99884033.5-.99884033 1 .49884033 1 .99884033 1zm-4 0c.5 0 1-.5 1-1s-.5-1-1-1-.99884033.5-.99884033 1 .49884033 1 .99884033 1zm8.00057947 0c.5002901 0 1.0005802-.5 1.0005802-1s-.5002901-1-1.0005802-1-.9994198.5-.9994198 1 .4991297 1 .9994198 1z"
                          fill="currentColor"/>
                </g>
            </svg>
            <h2>Health Chats</h2>
        </div>
        <div class="tile w1x2 active">
            <h3>Content and advises to follow</h3>
        </div>
        <div class="tile w1x1" id="television">
           <img src="{% static 'img/hero/stat.png' %}" height="120px" width="150px"  style="margin-top: 0px!important; margin-bottom: 0px!important;">
            <h2>statistics</h2>
        </div>

    </div>
</div>
</body>
</html>