App_auth/urls.py
from django.urls import path
from . import views


app_name = 'App_auth'

urlpatterns = [
    path('admin-signup/', views.admin_signup, name='admin-signup'),
    path('trainer-signup/', views.trainer_signup, name='trainer-signup'),
    path('member-signup/', views.member_signup, name='member-signup'),
    path('login/', views.login_system, name='login'),
    path('log-out/', views.logout_system, name='log-out'),

]

App_auth/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.utils.translation import gettext_lazy as _
from django.core.validators import *

# Create your models here.

gender_choice = (
    ("Male", "Male"),
    ("Female", "Female"),
    ("Third Gender", "Third Gender"),
)

phone_regex = RegexValidator(regex=r"^\+?(88)01[3-9][0-9]{8}$", message=_('Must add 880'))


class AdminModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='admin_user')
    phone_number = models.CharField(validators=[phone_regex], verbose_name=_("Admin_phone"), max_length=14)
    address = models.CharField(max_length=150)
    gender = models.CharField(choices=gender_choice, max_length=15)
    profile_picture = models.ImageField(upload_to='admin_picture')
    joining_date = models.DateField(auto_now_add=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return f"Admin - {self.user.first_name} {self.user.last_name}"


class TrainerModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='trainer_user')
    phone_number = models.CharField(validators=[phone_regex], verbose_name=_("Trainer_phone"), max_length=14)
    address = models.CharField(max_length=150)
    gender = models.CharField(choices=gender_choice, max_length=15)
    profile_picture = models.ImageField(upload_to='trainer_picture')
    joining_date = models.DateField(auto_now_add=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return f"Trainer - {self.user.first_name} {self.user.last_name}"


class MemberModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='member_user')
    phone_number = models.CharField(validators=[phone_regex], verbose_name=_("Member_phone"), max_length=14)
    address = models.CharField(max_length=150)
    age = models.PositiveIntegerField(null=True, blank=True)
    gender = models.CharField(choices=gender_choice, max_length=15)
    profile_picture = models.ImageField(upload_to='member_picture')
    joining_date = models.DateField(auto_now_add=True)
    my_trainer = models.ForeignKey(TrainerModel, on_delete=models.CASCADE, related_name='personal_trainer', blank=True,
                                   null=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return f"Member - {self.user.first_name} {self.user.last_name}"

App_auth/forms.py
from django import forms
from .models import *
from django.contrib.auth import forms as auth_form


class AdminUserForm(auth_form.UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class AdminForm(forms.ModelForm):
    class Meta:
        model = AdminModel
        exclude = ['user', 'joining_date', 'status']


class TrainerUserForm(auth_form.UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class TrainerForm(forms.ModelForm):
    class Meta:
        model = TrainerModel
        exclude = ['user', 'joining_date', 'status']


class MemberUserForm(auth_form.UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class MemberForm(forms.ModelForm):
    class Meta:
        model = MemberModel
        exclude = ['user', 'joining_date', 'status']





App_auth/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from django.shortcuts import render, HttpResponseRedirect, reverse
from .models import *
from .forms import *


# Create your views here.


def admin_signup(request):
    form1 = AdminUserForm()
    form2 = AdminForm()
    if request.method == 'POST':
        form1 = AdminUserForm(data=request.POST)
        form2 = AdminForm(request.POST, request.FILES)
        if form1.is_valid() and form2.is_valid():
            my_form1 = form1.save()
            my_form2 = form2.save(commit=False)
            my_form2.user = my_form1
            my_form2.save()
            admin_grp = Group.objects.get_or_create(name='ADMIN')
            admin_grp[0].user_set.add(my_form1)
            return HttpResponseRedirect(reverse('App_main:admin-dashboard'))
    return render(request, 'App_auth/admin_signup.html', context={'form1': form1, 'form2': form2})


def trainer_signup(request):
    form1 = TrainerUserForm()
    form2 = TrainerForm()
    if request.method == 'POST':
        form1 = TrainerUserForm(data=request.POST)
        form2 = TrainerForm(request.POST, request.FILES)
        if form1.is_valid() and form2.is_valid():
            my_form1 = form1.save()
            my_form2 = form2.save(commit=False)
            my_form2.user = my_form1
            my_form2.save()
            trainer_grp = Group.objects.get_or_create(name='TRAINER')
            trainer_grp[0].user_set.add(my_form1)
            return HttpResponseRedirect(reverse('App_main:trainer-dashboard'))
    return render(request, 'App_auth/trainer_signup.html', context={'form1': form1, 'form2': form2})


def member_signup(request):
    form1 = MemberUserForm()
    form2 = MemberForm()
    if request.method == 'POST':
        form1 = MemberUserForm(data=request.POST)
        form2 = MemberForm(request.POST, request.FILES)
        if form1.is_valid() and form2.is_valid():
            my_form1 = form1.save()
            my_form2 = form2.save(commit=False)
            my_form2.user = my_form1
            my_form2.save()
            member_grp = Group.objects.get_or_create(name='MEMBER')
            member_grp[0].user_set.add(my_form1)
            return HttpResponseRedirect(reverse('App_main:member-dashboard'))
    return render(request, 'App_auth/member_signup.html', context={'form1': form1, 'form2': form2})


def login_system(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            if request.user.groups.filter(name__in=['ADMIN']).exists():
                return HttpResponseRedirect(reverse('App_main:admin-dashboard'))
            elif request.user.groups.filter(name__in=['TRAINER']).exists():
                return HttpResponseRedirect(reverse('App_main:trainer-dashboard'))
            elif request.user.groups.filter(name__in=['MEMBER']).exists():
                return HttpResponseRedirect(reverse('App_main:member-dashboard'))
            else:
                return HttpResponseRedirect(reverse('App_auth:login'))
    return render(request, 'App_auth/login.html')


def logout_system(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_main:index'))

templates/App_auth/admin_signup.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>GWTS | Signup</title>
</head>

<body>

<style>
    header {
        margin-top: 45px;
    }

    h1 {
        font-size: 55px;
    }

    p {
        font-size: 17px;
    }

    body {
        height: 100vh !important;
        overflow-y: hidden;
        background: url("{% static 'img/hero/hero-2.jpg' %}") !important;
    }

    h1, p, label, legend {
        text-align: center;
        color: #e8efed;
        font-family: sans-serif;
    }
    form {
        background-color: black;
        opacity: 0.8!important;
        color: white;
        padding-top: 15px!important;
        padding-bottom: 15px!important;
        padding-left: 8px;
        padding-right: 8px;
    }

    fieldset {
        border: 1px solid #e8efed
    }

    fieldset:hover {
        box-shadow: 5px 5px 40px 5px #e8efed
    }

    .submit-button {
        text-align: center;
        padding: 5px;
        font-weight: bold;
        color: white;
        background-color: transparent;
        border-radius: 10px;
        border: 2px solid white;
        height: 40px;
        width: 50%;
    }

    .submit-button:hover {
        box-shadow: 5px 5px 40px 5px #e8efed;
        letter-spacing: 1px!important;
    }

    .btn-div {
        text-align: center;
    }
    .log {
        color: #f50c0c;
        font-size: 16px;
        text-decoration: none;
        margin-left: 5px;
    }
    .log:hover {
        color: #f50c0c;
        font-weight: bold;
        letter-spacing: 1px!important;
    }

    @media only screen and (max-width: 768px) {
        body {
            overflow-y: scroll;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
    }

</style>

<header>
    <h1>Sign up</h1>
    <p>Please, fill in the following information.</p>
</header>
<br></br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset style="text-align: center">
        <legend>User Information:</legend>
        <label for="first_name" style="margin-right: 3%; margin-left: 2%">First Name: {{ form1.first_name }}</label>
        <label for="last_name" style="margin-right: 3%">Last Name: {{ form1.last_name }}</label>
        <label for="username" style="margin-right: 3%">User Name: {{ form1.username }}</label>
        <label for="email" style="margin-right: 3%">Email Address: {{ form1.email }}</label>
    </fieldset>
    <br></br>
    <fieldset style="text-align: center">
        <legend>Create a password:</legend>
        <label for="password1" style="margin-right: 3%">New password: {{ form1.password1 }}</label>
        <label for="password2" style="margin-left: 3%">Confirm password: {{ form1.password2 }}</label>
    </fieldset>
    <br></br>
    <fieldset style="text-align: center">
        <legend>Basic Information:</legend>
        <label for="address" style="margin-right: 4%; margin-left: 2%">Address: {{ form2.address }}
        </label>
        <label for="phone" style="margin-right: 4%">Address: {{ form2.phone_number }}
        </label>
        <label for="gender" style="margin-right: 2%">Gender: {{ form2.gender }}
        </label>
        <label for="profile_pic" style="margin-left: 2%">Profile Picture: {{ form2.profile_picture }}
        </label>
    </fieldset>
    <br>
    <br>
    <div class="btn-div">
        <button type="submit" class="submit-button">Sign up</button>

    </div>
</form>
</body>
</html>

templates/App_auth/login.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>GWTS | Signup</title>
</head>

<body>

<style>
    header {
        margin-top: 45px;
    }

    h1 {
        font-size: 55px;
    }

    p {
        font-size: 17px;
    }

    body {
        height: 100vh !important;
        overflow-y: hidden;
        background: url("{% static 'img/hero/hero-2.jpg' %}") !important;
    }

    h1, p, label, legend {
        text-align: center;
        color: #e8efed;
        font-family: sans-serif;
    }
    form {
        background-color: black;
        opacity: 0.8!important;
        color: white;
        padding-top: 15px!important;
        padding-bottom: 15px!important;
        padding-left: 10%;
        padding-right: 10%;
        margin-left: 20%;
        margin-right: 20%;
    }

    fieldset {
        border: 1px solid #e8efed
    }

    fieldset:hover {
        box-shadow: 5px 5px 40px 5px #e8efed
    }

    .submit-button {
        text-align: center;
        padding: 5px;
        font-weight: bold;
        color: white;
        background-color: transparent;
        border-radius: 10px;
        border: 2px solid white;
        height: 40px;
        width: 50%;
    }

    .submit-button:hover {
        box-shadow: 5px 5px 40px 5px #e8efed;
        letter-spacing: 1px!important;
    }

    .btn-div {
        text-align: center;
    }
    .log {
        color: #f50c0c;
        font-size: 16px;
        text-decoration: none;
        margin-left: 5px;
    }
    .log:hover {
        color: #f50c0c;
        font-weight: bold;
        letter-spacing: 1px!important;
    }

    @media only screen and (max-width: 768px) {
        body {
            overflow-y: scroll;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
    }

</style>

<header>
    <h1>Member Login</h1>
    <p>We are eagerly waiting for your arrival</p>
</header>
<br>
<form method="post">
    {% csrf_token %}
    <fieldset style="text-align: center">
        <legend>My Username:</legend>
        <label for="username" style="margin-right: 3%">User Name: <input type="text" id="username" name="username"></label>
    </fieldset>
    <br>
    <br>
    <fieldset style="text-align: center">
        <legend>My Password:</legend>
        <label for="password" style="margin-right: 3%">Password: <input type="password" id="password"
                                                                             name="password"></label>
    </fieldset>
    <br>
    <br>
    <div class="btn-div">
        <button type="submit" class="submit-button">LOG IN</button>
        <br>
        <p style="font-size: 12px;">Already a Member???<a href="{% url 'App_auth:member-signup' %}" class="log"> SignUp Here >></a></p>
    </div>
</form>
</body>
</html>

templates/App_auth/member_signup.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>GWTS | Signup</title>
</head>

<body>

<style>
    header {
        margin-top: 45px;
    }

    h1 {
        font-size: 55px;
    }

    p {
        font-size: 17px;
    }

    body {
        height: 100vh !important;
        overflow-y: hidden;
        background: url("{% static 'img/hero/hero-2.jpg' %}") !important;
    }

    h1, p, label, legend {
        text-align: center;
        color: #e8efed;
        font-family: sans-serif;
    }
    form {
        background-color: black;
        opacity: 0.8!important;
        color: white;
        padding-top: 15px!important;
        padding-bottom: 15px!important;
        padding-left: 8px;
        padding-right: 8px;
    }

    fieldset {
        border: 1px solid #e8efed
    }

    fieldset:hover {
        box-shadow: 5px 5px 40px 5px #e8efed
    }

    .submit-button {
        text-align: center;
        padding: 5px;
        font-weight: bold;
        color: white;
        background-color: transparent;
        border-radius: 10px;
        border: 2px solid white;
        height: 40px;
        width: 50%;
    }

    .submit-button:hover {
        box-shadow: 5px 5px 40px 5px #e8efed;
        letter-spacing: 1px!important;
    }

    .btn-div {
        text-align: center;
    }
    .log {
        color: #f50c0c;
        font-size: 16px;
        text-decoration: none;
        margin-left: 5px;
    }
    .log:hover {
        color: #f50c0c;
        font-weight: bold;
        letter-spacing: 1px!important;
    }

    @media only screen and (max-width: 768px) {
        body {
            overflow-y: scroll;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
    }

</style>

<header>
    <h1>Sign up</h1>
    <p>Please, fill in the following information.</p>
</header>
<br></br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset style="text-align: center">
        <legend>User Information:</legend>
        <label for="first_name" style="margin-right: 3%; margin-left: 2%">First Name: {{ form1.first_name }}</label>
        <label for="last_name" style="margin-right: 3%">Last Name: {{ form1.last_name }}</label>
        <label for="username" style="margin-right: 3%">User Name: {{ form1.username }}</label>
        <label for="email" style="margin-right: 3%">Email Address: {{ form1.email }}</label>
    </fieldset>
    <br></br>
    <fieldset style="text-align: center">
        <legend>Create a password:</legend>
        <label for="password1" style="margin-right: 3%">New password: {{ form1.password1 }}</label>
        <label for="password2" style="margin-left: 3%">Confirm password: {{ form1.password2 }}</label>
    </fieldset>
    <br></br>
    <fieldset style="text-align: center">
        <legend>Basic Information:</legend>
        <label for="address" style="margin-right: 1%;">Address: {{ form2.address }}
        </label>
        <label for="phone" style="margin-right: 1%">Phone: {{ form2.phone_number }}
        </label>
        <label for="gender" style="margin-right: 1%">Gender: {{ form2.gender }}
        </label>
        <label for="age" style="margin-right: 1%;">Age: {{ form2.age }}
        </label>
        <label for="profile_pic" style="margin-left: 1%">Profile Picture: {{ form2.profile_picture }}
        </label>
    </fieldset>
    <br>
    <br>
    <div class="btn-div">
        <button type="submit" class="submit-button">Sign up</button>
        <br>
        <p style="font-size: 12px;">Already a Member???<a href="{% url 'App_auth:login' %}" class="log"> Login Here >></a></p>
    </div>
</form>
</body>
</html>

templates/App_auth/trainer_signup.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>GWTS | Signup</title>
</head>

<body>

<style>
    header {
        margin-top: 45px;
    }

    h1 {
        font-size: 55px;
    }

    p {
        font-size: 17px;
    }

    body {
        height: 100vh !important;
        overflow-y: hidden;
        background: url("{% static 'img/hero/hero-2.jpg' %}") !important;
    }

    h1, p, label, legend {
        text-align: center;
        color: #e8efed;
        font-family: sans-serif;
    }
    form {
        background-color: black;
        opacity: 0.8!important;
        color: white;
        padding-top: 15px!important;
        padding-bottom: 15px!important;
        padding-left: 8px;
        padding-right: 8px;
    }

    fieldset {
        border: 1px solid #e8efed
    }

    fieldset:hover {
        box-shadow: 5px 5px 40px 5px #e8efed
    }

    .submit-button {
        text-align: center;
        padding: 5px;
        font-weight: bold;
        color: white;
        background-color: transparent;
        border-radius: 10px;
        border: 2px solid white;
        height: 40px;
        width: 50%;
    }

    .submit-button:hover {
        box-shadow: 5px 5px 40px 5px #e8efed;
        letter-spacing: 1px!important;
    }

    .btn-div {
        text-align: center;
    }
    .log {
        color: #f50c0c;
        font-size: 16px;
        text-decoration: none;
        margin-left: 5px;
    }
    .log:hover {
        color: #f50c0c;
        font-weight: bold;
        letter-spacing: 1px!important;
    }

    @media only screen and (max-width: 768px) {
        body {
            overflow-y: scroll;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
    }

</style>

<header>
    <h1>Sign up</h1>
    <p>Please, fill in the following information.</p>
</header>
<br></br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset style="text-align: center">
        <legend>User Information:</legend>
        <label for="first_name" style="margin-right: 3%; margin-left: 2%">First Name: {{ form1.first_name }}</label>
        <label for="last_name" style="margin-right: 3%">Last Name: {{ form1.last_name }}</label>
        <label for="username" style="margin-right: 3%">User Name: {{ form1.username }}</label>
        <label for="email" style="margin-right: 3%">Email Address: {{ form1.email }}</label>
    </fieldset>
    <br></br>
    <fieldset style="text-align: center">
        <legend>Create a password:</legend>
        <label for="password1" style="margin-right: 3%">New password: {{ form1.password1 }}</label>
        <label for="password2" style="margin-left: 3%">Confirm password: {{ form1.password2 }}</label>
    </fieldset>
    <br></br>
    <fieldset style="text-align: center">
        <legend>Basic Information:</legend>
        <label for="address" style="margin-right: 4%; margin-left: 2%">Address: {{ form2.address }}
        </label>
        <label for="phone" style="margin-right: 4%">Address: {{ form2.phone_number }}
        </label>
        <label for="gender" style="margin-right: 2%">Gender: {{ form2.gender }}
        </label>
        <label for="profile_pic" style="margin-left: 2%">Profile Picture: {{ form2.profile_picture }}
        </label>
    </fieldset>
    <br>
    <br>
    <div class="btn-div">
        <button type="submit" class="submit-button">Sign up</button>
    </div>
</form>
</body>
</html>